if (${CMAKE_HOST_WIN32})
    enable_language(ASM_MASM)
    add_definitions(-DWIN32)
    add_definitions(-D_M_X64)
elseif (${CMAKE_HOST_APPLE})
    add_definitions(-D_MAC)
elseif (${CMAKE_HOST_UNIX})
    add_definitions(-DUNIX)
endif ()