function(abc_file out_var file)
    get_filename_component(path ${file} DIRECTORY)
    get_filename_component(name ${file} NAME_WLE)
    if (path)
        set(${out_var} ${path}/${name}.abc PARENT_SCOPE)
    else ()
        set(${out_var} ${name}.abc PARENT_SCOPE)
    endif ()
endfunction()

function(working_path out_var file)
    get_filename_component(file_abs ${file} ABSOLUTE)
    file(RELATIVE_PATH file_work ${working_directory} ${file_abs})
    set(${out_var} ${file_work} PARENT_SCOPE)
endfunction()